// <auto-generated />
using System;
using CotizacionesPersonales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace cotizacionesPersonales.Migrations
{
    [DbContext(typeof(CotizacionesContext))]
    [Migration("20190514182609_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CotizacionesPersonales.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionCliente");

                    b.Property<string>("EmailCliente");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("TelefonoCliente");

                    b.HasKey("ClienteID");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            ClienteID = 1,
                            DireccionCliente = "Santiago de los Caballeros",
                            EmailCliente = "yonaides@gmail.com",
                            NombreCliente = "Yonaides Tavares"
                        });
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteID");

                    b.Property<DateTime>("FechaCotizacion");

                    b.Property<decimal>("MontoTotal");

                    b.HasKey("CotizacionID");

                    b.HasIndex("ClienteID");

                    b.ToTable("cotizacion");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.CotizacionDetalle", b =>
                {
                    b.Property<int>("CotizacionDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CotizacionID");

                    b.Property<DateTime>("FechaCotizacion");

                    b.Property<int?>("IdClienteClienteID");

                    b.Property<int?>("IdServicioServicioID");

                    b.Property<decimal>("precioServicio");

                    b.HasKey("CotizacionDetalleID");

                    b.HasIndex("CotizacionID");

                    b.HasIndex("IdClienteClienteID");

                    b.HasIndex("IdServicioServicioID");

                    b.ToTable("cotizacionDetalle");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionServicio");

                    b.Property<string>("NombreServicio");

                    b.Property<decimal>("PrecioServicio");

                    b.HasKey("ServicioID");

                    b.ToTable("servicio");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.ServicioDetalle", b =>
                {
                    b.Property<int>("ServicioDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionDetalleServicio");

                    b.Property<int?>("ServicioID");

                    b.HasKey("ServicioDetalleID");

                    b.HasIndex("ServicioID");

                    b.ToTable("servicioDetalle");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.Cotizacion", b =>
                {
                    b.HasOne("CotizacionesPersonales.Models.Cliente", "ClienteId")
                        .WithMany("Cotizacion")
                        .HasForeignKey("ClienteID");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.CotizacionDetalle", b =>
                {
                    b.HasOne("CotizacionesPersonales.Models.Cotizacion")
                        .WithMany("CotizacionDetalle")
                        .HasForeignKey("CotizacionID");

                    b.HasOne("CotizacionesPersonales.Models.Cliente", "IdCliente")
                        .WithMany()
                        .HasForeignKey("IdClienteClienteID");

                    b.HasOne("CotizacionesPersonales.Models.Servicio", "IdServicio")
                        .WithMany()
                        .HasForeignKey("IdServicioServicioID");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.ServicioDetalle", b =>
                {
                    b.HasOne("CotizacionesPersonales.Models.Servicio", "ServicioId")
                        .WithMany("ServicioDetalle")
                        .HasForeignKey("ServicioID");
                });
#pragma warning restore 612, 618
        }
    }
}
