// <auto-generated />
using System;
using CotizacionesPersonales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace cotizacionesPersonales.Migrations
{
    [DbContext(typeof(CotizacionesContext))]
    [Migration("20190514164655_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CotizacionesPersonales.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionCliente");

                    b.Property<string>("EmailCliente");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("TelefonoCliente");

                    b.HasKey("ClienteID");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteID");

                    b.Property<DateTime>("FechaCotizacion");

                    b.Property<decimal>("MontoTotal");

                    b.HasKey("CotizacionID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Cotizacion");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.CotizacionDetalle", b =>
                {
                    b.Property<int>("CotizacionDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CotizacionID");

                    b.Property<DateTime>("FechaCotizacion");

                    b.Property<int?>("IdClienteClienteID");

                    b.Property<decimal>("MontoTotal");

                    b.HasKey("CotizacionDetalleID");

                    b.HasIndex("CotizacionID");

                    b.HasIndex("IdClienteClienteID");

                    b.ToTable("CotizacionDetalle");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.Cotizacion", b =>
                {
                    b.HasOne("CotizacionesPersonales.Models.Cliente", "ClienteId")
                        .WithMany("Cotizacion")
                        .HasForeignKey("ClienteID");
                });

            modelBuilder.Entity("CotizacionesPersonales.Models.CotizacionDetalle", b =>
                {
                    b.HasOne("CotizacionesPersonales.Models.Cotizacion")
                        .WithMany("CotizacionDetalle")
                        .HasForeignKey("CotizacionID");

                    b.HasOne("CotizacionesPersonales.Models.Cliente", "IdCliente")
                        .WithMany()
                        .HasForeignKey("IdClienteClienteID");
                });
#pragma warning restore 612, 618
        }
    }
}
